<a href="https://colab.research.google.com/github/prabhnoor14/walmart-hurricane-project/blob/main/notebooks/team_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/prabhnoor14/walmart-hurricane-project

fatal: destination path 'walmart-hurricane-project' already exists and is not an empty directory.

In [2]:
Decisions = []

def log_decision( decision, row_affected):
  Decisions.append({'decision': decision, 'rows': row_affected})
  print(f'{decision}({row_affected} row(s))')
def show_log():
  return pd.DataFrame(Decisions)

In [3]:
import pandas as pd

def load_table(PATH):
  try:
      df = pd.read_csv(PATH)
      df.head()
      return df
  except FileNotFoundError:
      print('File not found. Please check the file exist or double check the path')
      return None

In [4]:
def table_info(df):
  print('\nTable infor:')
  df.info()
  print('\nNull values for each column \n')
  print(df.isna().sum())                  # missing values per column
  print('\nDuplicated Rows Count: ',df.duplicated().sum())           # fully identical rows

In [5]:
walmart_transactions = load_table('/content/walmart-hurricane-project/data/walmart_transactions.csv')
table_info(walmart_transactions)

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25562 entries, 0 to 25561
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  25562 non-null  object
 1   store_id        25562 non-null  object
 2   timestamp       24676 non-null  object
 3   sku             25562 non-null  object
 4   product_name    25562 non-null  object
 5   category        25562 non-null  object
 6   quantity        25562 non-null  int64
 7   unit_price      25562 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.6+ MB

Null values for each column

transaction_id      0
store_id            0
timestamp         886
sku                 0
product_name        0
category            0
quantity            0
unit_price          0
dtype: int64

Duplicated Rows Count:  30

In [8]:
distribution_centers = load_table('/content/walmart-hurricane-project/data/distribution_centers.csv')
table_info(distribution_centers)

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   dc_id                   5 non-null      object
 1   dc_name                 5 non-null      object
 2   city                    5 non-null      object
 3   state                   5 non-null      object
 4   avg_daily_shipments     5 non-null      int64
 5   surge_capacity          5 non-null      object
 6   distance_to_orlando_mi  5 non-null      int64
 7   cost_per_shipment       4 non-null      float64
dtypes: float64(1), int64(2), object(5)
memory usage: 452.0+ bytes

Null values for each column

dc_id                     0
dc_name                   0
city                      0
state                     0
avg_daily_shipments       0
surge_capacity            0
distance_to_orlando_mi    0
cost_per_shipment         1
dtype: int64

Duplicated Rows Count:  0

In [10]:
store_locations = load_table('/content/walmart-hurricane-project/data/store_locations.csv')
table_info(store_locations)

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    14 non-null     object
 1   store_name  14 non-null     object
 2   city        14 non-null     object
 3   state       14 non-null     object
 4   zip_code    14 non-null     int64
 5   latitude    13 non-null     float64
 6   longitude   13 non-null     float64
 7   region      14 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.0+ KB

Null values for each column

store_id      0
store_name    0
city          0
state         0
zip_code      0
latitude      1
longitude     1
region        0
dtype: int64

Duplicated Rows Count:  0

In [12]:
product_catalog = load_table('/content/walmart-hurricane-project/data/product_catalog.csv')
table_info(product_catalog)

Table infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sku           45 non-null     object
 1   product_name  45 non-null     object
 2   category      45 non-null     object
 3   subcategory   32 non-null     object
 4   unit_cost     40 non-null     float64
 5   supplier      45 non-null     object
 6   package_size  45 non-null     object
dtypes: float64(1), object(6)
memory usage: 2.6+ KB

Null values for each column

sku              0
product_name     0
category         0
subcategory     13
unit_cost        5
supplier         0
package_size     0
dtype: int64

Duplicated Rows Count:  0

In [13]:
def drop_duplicate(frame):
  clean = frame.drop_duplicates().copy() # saving a copy of the frame after dropping duplicates to not alter the original frame
  print('rows:', len(frame), '->', len(clean))
  return clean

In [14]:
print('Count of rows after dropping duplicated rows from the product_catalog table')
product_catalog_copy = drop_duplicate(product_catalog)
print('Count of rows after dropping duplicated rows from the walmart_transactions table')
walmart_transactions_copy = drop_duplicate(walmart_transactions)
print('Count of rows after dropping duplicated rows from the distribution_centers table')
distribution_centers_copy = drop_duplicate(distribution_centers)
print('Count of rows after dropping duplicated rows from the store_location table')
store_locations_copy = drop_duplicate(store_locations)

Count of rows after dropping duplicated rows from the product_catalog table
rows: 45 -> 45
Count of rows after dropping duplicated rows from the walmart_transactions table
rows: 25562 -> 25532
Count of rows after dropping duplicated rows from the distribution_centers table
rows: 5 -> 5
Count of rows after dropping duplicated rows from the store_location table
rows: 14 -> 14

In [15]:
def transform_price_columns(df, column_name):
  df[column_name] = (df[column_name].astype(str)
                     .str.replace('$','',regex=False)
                     .str.strip().astype(float))
  return df

In [16]:
transform_price_columns(walmart_transactions_copy, 'unit_price')

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,PEANUT BUTTER,Grocery,1,3.15
1,TXN000759,fl-412,2024-09-13 20:30:20,CNSOUP-01,CANNED SOUP,GROCERY,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,ELECTRONICS,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24pk,Alcoholic Beverages,3,18.82
...,...,...,...,...,...,...,...,...
25557,TXN020201,FL-105,2024-09-03T18:28:07,DIAPERS-3,Diapers Size 3,baby,2,24.32
25558,TXN014835,FL-239,09-26-2024 08:47:08,CARDS-01,Playing Cards,Games & Entertainment,3,5.00
25559,TXN002434,fl-239,16-Sep-2024 16:39,PAPERTOWEL6,Paper Towels 6-Roll,household,2,7.78
25560,TXN014739,FL-710,2024-09-25 17:08:35,CHRG-PORT,PORTABLE CHARGER,electronics,1,24.18
25561,TXN010981,FL-105,24-Sep-2024 06:32,DIAP-S3,Diapers Size 3,baby,2,24.90

**Handling Timestamp**

In [17]:
walmart_transactions_copy['timestamp'] = pd.to_datetime(walmart_transactions_copy['timestamp'],errors='coerce', format ='mixed')
missing_date = walmart_transactions_copy['timestamp'].isna().sum()
print('count failed timestamps :',missing_date)

walmart_transactions_copy['hour'] = walmart_transactions_copy['timestamp'].dt.hour
walmart_transactions_copy[walmart_transactions_copy['timestamp'].isna()]

count failed timestamps : 884

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price,hour
24,TXN006442,FL-710,NaT,PAPERTOWEL6,Paper Towels,Household,1,7.82,NaN
45,TXN021737,FL-619,NaT,TP-12,TOILET PAPER 12PK,HOUSEHOLD,2,9.74,NaN
46,TXN017349,FL-501,NaT,CANDLE-EMRG,Emergency Candles,emergency,1,5.78,NaN
83,TXN019304,FL-619,NaT,BATT-100,BATTERIES AA 4PK,Emergency,1,6.56,NaN
138,TXN012731,FL_239,NaT,PT-12,POPTART-STRAWBERRY,BREAKFAST,4,3.56,NaN
...,...,...,...,...,...,...,...,...,...
25505,TXN022501,fl-239,NaT,BATT_AA_4PK,AA Batteries (4-pack),emergency,1,6.28,NaN
25508,TXN022939,FL-619,NaT,HDTARP-01,HD Tarp,emergency,2,20.07,NaN
25548,TXN005477,fl-445,NaT,LED-FLASH,LED Flashlight,emergency,1,13.35,NaN
25549,TXN003817,FL-619,NaT,BFORM-01,BABY FORMULA,BABY,1,28.78,NaN
25552,TXN010660,FL-710,NaT,BFORM-01,Infant Formula,BABY,1,29.67,NaN

In [18]:
table_info(walmart_transactions_copy)

Table infor:
<class 'pandas.core.frame.DataFrame'>
Index: 25532 entries, 0 to 25561
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  25532 non-null  object
 1   store_id        25532 non-null  object
 2   timestamp       24648 non-null  datetime64[ns]
 3   sku             25532 non-null  object
 4   product_name    25532 non-null  object
 5   category        25532 non-null  object
 6   quantity        25532 non-null  int64
 7   unit_price      25532 non-null  float64
 8   hour            24648 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 1.9+ MB

Null values for each column

transaction_id      0
store_id            0
timestamp         884
sku                 0
product_name        0
category            0
quantity            0
unit_price          0
hour              884
dtype: int64

Duplicated Rows Count:  0

**Handling NaN for the cost_per_shipment**

In [19]:
distribution_centers_copy

,dc_id,dc_name,city,state,avg_daily_shipments,surge_capacity,distance_to_orlando_mi,cost_per_shipment
0,DC-JAX,Jacksonville Distribution Center,Jacksonville,FL,500,1000,141,245.0
1,DC-ATL,Atlanta Distribution Center,Atlanta,GA,400,700,438,412.5
2,DC-DAL,Dallas Distribution Center,Dallas,TX,300,600,1108,687.0
3,DC-MIA,Miami Distribution Center,Miami,FL,350,~750,235,298.0
4,DC-BHM,Birmingham Distribution Center,Birmingham,AL,250,500,503,NaN

In [20]:
missing_cost_per_shipment =  distribution_centers_copy['cost_per_shipment'].isna().sum()
distribution_centers_copy['cost_per_shipment'] = distribution_centers_copy['cost_per_shipment'].fillna(distribution_centers_copy['cost_per_shipment'].median())
log_decision('Filling missing values in cost per shipment column with the median of all cost of shipments',missing_cost_per_shipment)

Filling missing values in cost per shipment column with the median of all cost of shipments(1 row(s))

**Handling NaN for the latitude and longitute**

**Handling NaN for the subcategory**

In [22]:
product_catalog_copy_with_na_sum = len(product_catalog_copy[product_catalog_copy['subcategory'].isna()])

SUBC_MAP = {
    'pop-tarts strawberry': 'Pop-Tarts',
    'Pop-Tarts Strawberry': 'Pop-Tarts',
    'Water - 24 Pack': 'Bottled',
    'FLASHLIGHT LED':'Flashlight',
    'Light Beer (24-pack)':'Light',
    'Monopoly Board Game':'Playing',
    'Board Game - Monopoly': 'Playing',
    'Canned Soup':'Canned',
    'First Aid Kit':'First',
    'PORTABLE CHARGER':'Portable',
    'Baby Formula':'Baby',
    'Heavy Duty Tarp': 'Tarp'

}

product_catalog_copy['subcategory'] = product_catalog_copy['subcategory'].fillna(product_catalog_copy['product_name'].map(SUBC_MAP))
log_decision('Filled missing values in the subcategory column with mapped categories',product_catalog_copy_with_na_sum)

Filled missing values in the subcategory column with mapped categories(13 row(s))

**TODO: Fixing inventory_and_sales.db File**